'use client'

import { useEffect, useMemo, useState } from 'react'
import { Activity, ArrowUpRight, Box, CreditCard, LayoutDashboard, Package, Receipt, Search, ShoppingCart, Users, Warehouse } from 'lucide-react'

type Product={id:string;name:string;category:string;price:number;weight:number}; type Customer={id:string;name:string;email:string;region:string;tier:string}; type Order={id:string;customer_id:string;total:number;status:string;items:{product_id:string;quantity:number}[]};
const API='http://127.0.0.1:8000/api'
const money=(n:number)=>`$${n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`

function Metric({label,value,detail,icon:Icon}:{label:string;value:string;detail:string;icon:any}){return <div className="metric"><div className="metric-top"><span>{label}</span><Icon size={16}/></div><strong>{value}</strong><small>{detail}</small></div>}
function Nav({active,setActive}:{active:string;setActive:(x:string)=>void}){const items=[['Overview',LayoutDashboard],['Products',Package],['Orders',ShoppingCart],['Customers',Users],['Inventory',Warehouse],['Invoices',Receipt]];return <aside><div className="brand"><div className="brand-mark">O</div><div><b>OrderFlow</b><small>commerce operations</small></div></div><nav>{items.map(([name,Icon]:any)=><button className={active===name?'active':''} onClick={()=>setActive(name)} key={name}><Icon size={17}/>{name}</button>)}</nav><div className="side-footer"><div className="status-dot"/> API connected <span>v1.0</span></div></aside>}

export default function Page(){const [active,setActive]=useState('Overview'); const [products,setProducts]=useState<Product[]>([]); const [customers,setCustomers]=useState<Customer[]>([]); const [orders,setOrders]=useState<Order[]>([]); const [health,setHealth]=useState('checking'); const [query,setQuery]=useState('');
 useEffect(()=>{Promise.all([fetch(`${API}/products`).then(r=>r.json()),fetch(`${API}/orders`).then(r=>r.json()),fetch(`${API}/customers/CUSTOMER-001`).then(r=>r.json()),fetch(`${API}/health`).then(r=>r.json())]).then(([p,o,c,h])=>{setProducts(p.products);setOrders(o);setCustomers([c]);setHealth(h.status)}).catch(()=>{setHealth('offline'); setProducts([{id:'PROD-001',name:'Aero Wireless Headphones',category:'electronics',price:129.99,weight:.4},{id:'PROD-002',name:'Orbit Mechanical Keyboard',category:'electronics',price:149,weight:.9},{id:'PROD-003',name:'Field Notes Journal',category:'books',price:24,weight:.3},{id:'PROD-004',name:'The Craft of Systems',category:'books',price:42,weight:.7},{id:'PROD-005',name:'Canvas Utility Jacket',category:'clothing',price:180,weight:1.1}]); setOrders([{id:'ORDER-001',customer_id:'CUSTOMER-001',total:180.77,status:'paid',items:[]}]); setCustomers([{id:'CUSTOMER-001',name:'Maya Chen',email:'maya@example.com',region:'US',tier:'gold'}])})},[])
 const revenue=useMemo(()=>orders.reduce((s,o)=>s+o.total,0),[orders]); const filtered=products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));
 return <div className="app-shell"><Nav active={active} setActive={setActive}/><main className="content"><header><div><div className="eyebrow">OPERATIONS / {active.toUpperCase()}</div><h1>{active==='Overview'?'Good morning, Maya.':'Commerce operations'}</h1><p className="subhead">A live view of your catalog, orders, and pricing engine.</p></div><div className="header-actions"><span className={`api-pill ${health}`}><Activity size={14}/>{health==='ok'?'API operational':'API '+health}</span><div className="avatar">MC</div></div></header>
 {active==='Overview'?<><section className="metrics"><Metric label="Gross revenue" value={money(revenue)} detail="Across 2 settled orders" icon={CreditCard}/><Metric label="Active orders" value={`${orders.length}`} detail="100% payment success" icon={ShoppingCart}/><Metric label="Catalog items" value={`${products.length}`} detail="Across 5 categories" icon={Package}/><Metric label="Inventory health" value="94.2%" detail="3 items need attention" icon={Warehouse}/></section><section className="grid-main"><div className="panel"><div className="panel-head"><div><h2>Recent orders</h2><p>Latest activity from the order pipeline</p></div><button className="text-btn" onClick={()=>setActive('Orders')}>View all <ArrowUpRight size={14}/></button></div><div className="table"><div className="tr th"><span>Order</span><span>Customer</span><span>Status</span><span className="right">Total</span></div>{orders.map((o,i)=><div className="tr" key={o.id}><span className="mono">{o.id}</span><span>{i?'Jon Bell':'Maya Chen'}</span><span><em className="tag paid">{o.status}</em></span><span className="right bold">{money(o.total)}</span></div>)}</div></div><div className="panel signal"><div className="panel-head"><div><h2>Pricing engine</h2><p>Deterministic rule evaluation</p></div><span className="live">LIVE</span></div><div className="pipeline"><div>Cart items <b>→</b></div><div>Discounts <b>→</b></div><div>Tax & shipping <b>→</b></div><div className="final">Final total</div></div><div className="rule"><span className="rule-dot"/> Coupon stacking protection active</div></div></section></>:<section className="panel page-panel"><div className="panel-head"><div><h2>{active}</h2><p>{active==='Products'?'Search and review your deterministic product catalog.':active==='Orders'?'Track order lifecycle and payment status.':active==='Customers'?'Customer profiles and loyalty segments.':'Operational records from the OrderFlow API.'}</p></div>{active==='Products'&&<label className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products"/></label>}</div>{active==='Products'?<div className="product-grid">{filtered.map(p=><div className="product" key={p.id}><div className="product-icon">{p.category.slice(0,2).toUpperCase()}</div><div><b>{p.name}</b><small className="mono">{p.id} · {p.category}</small></div><strong>{money(p.price)}</strong></div>)}</div>:<div className="table">{(active==='Orders'?orders:customers).map((row:any)=><div className="tr" key={row.id}><span className="mono">{row.id}</span><span>{row.name||row.customer_id||row.status}</span><span>{row.email||row.status||'Active'}</span><span className="right bold">{row.total?money(row.total):row.tier||'—'}</span></div>)}</div>}</section>}
 <footer><span>OrderFlow platform</span><span>Deterministic local environment · Last sync fixed seed</span></footer></main></div>}
